name: sound_alert_app
description: Community sound alert app with on-device TFLite classification
publish_to: "none"

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.12.0
  cloud_firestore: ^4.8.0
  firebase_messaging: ^14.5.0
  google_maps_flutter: ^2.4.5
  tflite_flutter: ^0.10.0
  tflite_flutter_helper: ^0.5.0
  record: ^4.4.0
  path_provider: ^2.0.14
  flutter_local_notifications: ^14.0.0
  vibration: ^1.7.4
  provider: ^6.0.5
  uuid: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
